version: 0.0
os: linux
files:
  - source: /dist
    destination: //usr/share/nginx/html
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
