version: 0.0
os: linux
files:
  - source: /FrontEnd/dist
    destination: //usr/local/nginx/html
  - source: /API/target/API-0.0.1.war
    destination: //usr/share/tomcat8/webapps
hooks:
  ApplicationStop:
    - location: aws_scripts/stop_servers
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws_scripts/start_servers
      timeout: 300
      runas: root
