version: 0.2

phases:
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - aws ec2 authorize-security-group-ingress --group-id sg-3eb4d757 --protocol tcp --port 8081 --cidr $IP --region eu-west-2
  build:
    commands:
      - echo Build started on `date`
      - mvn -B package
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - aws ec2 revoke-security-group-ingress --group-id sg-3eb4d757 --protocol tcp --port 8081 --cidr $IP --region eu-west-2
      - echo Build completed on `date`
artifacts:
  files:
    - API/target/API-0.0.1.war
    - FrontEnd/target/FrontEnd-1.0-SNAPSHOT-bin.zip